source "https://rubygems.org"

gem "jekyll"
gem "minimal-mistakes-jekyll"
gem "jekyll-include-cache"
gem "jekyll-paginate"
gem "jekyll-sitemap"
gem "jekyll-feed"
gem "jekyll-archives"
gem "jekyll-toc"
